### ISSUE TITLE
Add Possibility to download files in InternetExplorer

### ISSUE THREAD

**Issue by raczeja** [ObjectivityBSS/Test.Automation#4]

**Comment by SuperExpectation** [comment]
Issue:
For example under Objectivity.Test.Automation.Tests.MSTest
1:Recording log and taking snapshots function is not stable, sometime it was there, and sometime it wasn't there.  

2:System delete Test-Result no matter value of "DeleteDeploymentDirectoryAfterTestRunIsComplete" is true or false.

If something i missed or make mistake, please let me know.
Thanks in advance.

**Comment by raczeja** [comment]
first of all please rise separate issue, because your problem is not related to that one. Any way try to use Runsettings.runsettings included in solution: https://msdn.microsoft.com/en-us/library/jj635153.aspx , http://stackoverflow.com/questions/14920754/how-to-turn-off-test-deployment-in-vs2012
